

#### POWERLINE DAEMON
export PATH="$HOME/.local/bin:$PATH"
powerline-daemon -q


#### POWERLINE FOR BASH
if [ -f ~/.local/lib/python2.7/site-packages/powerline/bindings/bash/powerline.sh ]; then
      . ~/.local/lib/python2.7/site-packages/powerline/bindings/bash/powerline.sh
fi


#### CUSTOM ALIASES
if [ -f ~/.dotfiles/aliases ]; then
      . ~/.dotfiles/aliases
fi


#### TMUXINATOR
if [ -f ~/.bin/tmuxinator.bash ]; then
      . ~/.bin/tmuxinator.bash
fi

