

#### POWERLINE DAEMON
export PATH="$HOME/.local/bin:$PATH"
powerline-daemon -q


#### POWERLINE FOR ZSH
if [ -f ~/.local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh ]; then
      . ~/.local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh
fi


#### CUSTOM ALIASES
if [ -f ~/.dotfiles/aliases ]; then
      . ~/.dotfiles/aliases
fi


#### TMUXINATOR
if [ -f ~/.bin/tmuxinator.zsh ]; then
      . ~/.bin/tmuxinator.zsh
fi


#### RELOAD ZSH CONFIG
alias reloadzsh="source ~/.zshrc"


# Auto Correct Commands
# setopt CORRECT

